FROM ubuntu:14.04
MAINTAINER hardik.patel@cbp.dhs.gov
RUN apt-get update
RUN apt-get install -y vim curl wget
RUN apt-get update
RUN apt-get install -y python-setuptools
RUN easy_install pip
RUN apt-get install -y fabric 
